Roadou/JVCForumRollback

JVCForumRollback.meta.js
JVCForumRollback.user.js

**Auto Update** => J'attends qu'elle soit merge pour push sur jvscript
Sans ça => **ça va obliger les gens à update à chaque fois à la main**, donc j'attends que tu merge pour publier le script
J'ai aussi ajouter la "license mit" dans l'en tête du JS
**(En fait j'ai surtout mis en MIT si jamais un jour le script est abandonné que n'importe qui puisse le reprendre.)**

[Important] Auto Update => J'attends qu'elle soit merge pour push sur jvscript

---

README.md

Changement description pour rentre l'installation + intuitive
à toi de voir pour celui-là ça change juste la description

(Factultatif) Changement bouton installation

---

README.md

[Description] ajout lien jvscript

---

JVCForumRollback.meta.js
JVCForumRollback.user.js

Lien forum Genesis sur le bloc forum

Lien forum Genesis

---

JVCForumRollback.meta.js
JVCForumRollback.user.js

(Anciennes pubs qui buggaient) j'ai enlevé car y'avait des bugs sans bloqueurs
Nonobstant je sais que 90% des gens avec des Tampermonkey ont surement AdBlock ou autre, mais je préfère corriger l'ancien code => parce qu'il faisait des pop-up au mauvais endroit.
=> y'a plus de pub avec ou sans bloqueur sur la page d'accueil forum .

[Important] j'ai enlevé les pubs qui buggaient avec l'ancienne mise en page.

---

JVCForumRollback.meta.js
JVCForumRollback.user.js

(Ajustement) Eviter saute sur le forum genesis

(Ajustement) Eviter saute sur le forum genesis

---

JVCForumRollback.meta.js
JVCForumRollback.user.js

(Retour en arrière) eviter du fouc
Désolé khey je test un peu . Je vais arreter.
J'essaye d'eviter les sautes à l'affichage mais c'est pas evident .
**Je fait mon max pour que la page pop en entier sans avoir des trucs qui bougent à droite et à gauche.**

(Retour en arrière) eviter du fouc

---

JVCForumRollback.meta.js
JVCForumRollback.user.js

Comme la précédente j'ai clean un peu le code de truc qui n'avait vraiment pas besoin.
Sauf que cette fois je me suis pas fail
Bref j'arrête un peu sur le script Je pense que là il est vraiment au point si tu veux en discuter avec moi des changements que j'ai fait car en fait c'est très technique j'avais utilisé mon propre système de cache pour éviter d'avoir des éléments qui POP au chargement de la page le but c'était d'avoir le truc le plus fluide possible.

 (Mise en cache tu top forum) Clean code simplifcation

---

JVCForumRollback.meta.js
JVCForumRollback.user.js

Ouais désolé khey j'ai fait beaucoup de tests pour essayer d'obtenir la version la plus rapide du coup il semble que ça soit ça.
Le top forum est mis en cache dès qu'il est récupéré un cache créé par le script comme ça ça évite le popping et j'ai fait en sorte de minimiser les calculs lors du premier affichage tout est récupéré via le cache et s'il n'existe pas effectivement il peut y avoir un peu de popping mais c'est que lors du premier chargement ou s'il y a une modification du top forum ça va légèrement pop à chaque changement en fait

(Optimisation finale et structuration code) Je pense pour le coup que c'est la bonne en terme de performance

---

JVCForumRollback.meta.js
JVCForumRollback.user.js

(debug) **j'avais zappé un truc** cette fois c'est bon
Je te MP pour t'expliquer vite fait **je suis désolé pour la vague de pr** mais j'ai essayé d'optimiser le truc rapidement et j'avais pas mal d'erreurs là normalement c'est bon le script devrait rester inchangé pour un moment.

(debug) j'avais zappé un truc cette fois c'est bon

---

JVCForumRollback.meta.js
JVCForumRollback.user.js

(simplification + eviter poping)

(simplification + eviter poping)

---

README.md

(modification fichier présentation) 
Ajout de précision pour kiwi (mobile)
Ajout de violentmonkey
Ajout de "userscript" pour ios.
Aucune modification sur le script en lui même.
Juste la page de présentation.

(modification fichier présentation) aucune modification sur le script

---

JVCForumRollback.meta.js
JVCForumRollback.user.js

ajout forum switch 2

---

JVCForumRollback.meta.js
JVCForumRollback.user.js

Ajout forum Nintendo Switch 2 
+ petite mise à jour pour alléger

ajout forum nintendo switch 2 v2

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

6.6.5 mise à jour image top jeu fm 2024 (cf change log)

6.6.5 mise à jour image top jeu fm 2024 (cf change log)

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

Passage en second du forum switch 2 pour être raccord avec le site et ne pas perdre les habitués
on verra plus tard quand elle sera top forum

(maj mineure) passage en second du forum switch 2

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

il est bien plus fréquenté et ça sera surement le cas d'ici à l'annonce d'avril et flemme de changer après le script.

(maj mineure reverse) re-passage en 1er du forum switch 2

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

optimisation code et restauration ancien valeur en cas de retour en arrière

(clean code)

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

Je suis revenu sur une version précédente j'avais auparavant viré l'image avec le top jeu, car les images de JVC ne correspondent pas et n'ont pas le bon ratio.
Seulement plusieurs personnes préféraient l'ancienne version et je suis d'accord.
Donc voilà retour en arrière et faudra trouver une solution pour le futur.

(RollBack) Remise forum jeu tendance (toujours pas de soluce à long terme) ^^

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js
README.md

Commentaire code en cas de retour en arrière ne change rien à l'exécution
README.md mis à jour pour virer le logo Tampermonkey car il ne marche pas en mode nuit.

(commentaire code) + README.md mis à jour

---

README.md

Update README.md pour la fin du mv2 sur chrome

Update README.md pour la fin du mv2 sur chrome

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

6.8.6 ajout miniature gta

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

6.8.7 (miniature GTA VI définitive j'espère )
Je n'ai toujours pas de solution pour le top jeu sauf exception à la main .
Peut-être en 2027.

6.8.7 (miniature GTA VI définitive j'espère )

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

Bon comme d'hab hein la miniature de Assassin's Creed shadow et remplacer si elle arrive en top forum
faudrait Trouver un autre système qu'update le script Mais j'ai la flemme
Pour le moment on fait comme ça on verra plus tard

(miniature AC shadow) 

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

Ajout d'une exception sur clair obscur
Ratio l'image top forum

(ratio ficher jeu) clair obscur

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

Préparation d'un nouveau système qui redirigera vers les forums favoris pour l'image d'en tête.
C'est en commentaire, rien n'est actif. 
C'est de la finition en vue de pouvoir switcher le système, ça n'a aucun impact sur l'exécution du code.

(Préparation d'un nouveau système v2) Forums favoris

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

clean branche backup 
Cette branche est prévue en cas de pr extérieur si je dois te consulter bon elle a toujours pas servi :noel:

clean branche backup

---

.github/workflows/generate-meta.yml
CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

Ajout d'une action automatisée, en gros le fichier Meta est écrit automatiquement maintenant.
C'est un doublon qui permet des mises à jour il n'y a aucun intérêt à le mettre à jour manuellement.
C'est un composant officiel de github j'ai vérifié 46 fois, Tout est 100% safe.
Le Bot se contente à chaque mise à jour du fichier principal, De mettre à jour le fichier Meta avec la bonne version.

(mise à jour pour automatiser) Ajout une action automatisée et documentation du script en cas de reprise.

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

(test) Pour voir juste si cette fois le Bot ignore de refaire la modification 
Ça évite les erreurs de permission une double commit.
Comme je disais tu peux l'utiliser toi même sur le dépôt.
Je l'utilise sur mon fork je préfère travailler sur mon fork pour éviter des erreurs.
Donc dans la configuration actuelle Toi seul peut modifier directement le fichier Javascript depuis ton dépôt.
Je pourrais faire autrement mais je préfère garder les autorisations minimales.

(test) Pour voir juste si cette fois le Bot ignore de refaire la modification 

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

Grosse factorisation des fonctions post affichage.
Simplification de la lecture, nommage des variables un peu plus claires.

[Clean code important]

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

Repassage des liens absolu en relatif, y a certaines variables qui avaient changé suite à la simplification du code Ice.
Normalement ça devrait être bon cette fois-ci.

(repassage des liens absolus en relatif) ... désolé pour le test de prod sur le terrain :peur:

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

Préparation pour la miniature de Pokémon Z + clarification change log

Préparation pour la miniature de Pokémon Z + clarification change log

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

[maj light] clean code

---

CHANGELOG.md
JVCForumRollback.meta.js
JVCForumRollback.user.js

7.1.2 : [MINIATURE RATIO] SILKSONG ratio card

7.1.2 : [MINIATURE RATIO] SILKSONG ratio card
